In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('https://raw.github.com/YBIFoundation/Dataset/main/Spam%20Email.csv')


In [3]:
df.head()

ID Mail                                               Text  Label
0   1  ham          Subject: christmas tree farm pictures\r\n      0
1   2  ham  Subject: vastar resources , inc .\r\ngary , pr...      0
2   3  ham  Subject: calpine daily gas nomination\r\n- cal...      0
3   4  ham  Subject: re : issue\r\nfyi - see note below - ...      0
4   5  ham  Subject: meter 7268 nov allocation\r\nfyi .\r\...      0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      5171 non-null   int64 
 1   Mail    5171 non-null   object
 2   Text    5171 non-null   object
 3   Label   5171 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 161.7+ KB


In [5]:
df.columns

Index(['ID', 'Mail', 'Text', 'Label'], dtype='object')

In [6]:
df.shape

(5171, 4)

In [7]:
y=df['Label']

In [8]:
y.shape

(5171,)

In [9]:
y

0       0
1       0
2       0
3       0
4       0
       ..
5166    1
5167    1
5168    1
5169    1
5170    1
Name: Label, Length: 5171, dtype: int64

In [10]:
X=df['Text']

In [11]:
X.shape

(5171,)

In [12]:
X

0               Subject: christmas tree farm pictures\r\n
1       Subject: vastar resources , inc .\r\ngary , pr...
2       Subject: calpine daily gas nomination\r\n- cal...
3       Subject: re : issue\r\nfyi - see note below - ...
4       Subject: meter 7268 nov allocation\r\nfyi .\r\...
                              ...                        
5166    Subject: our pro - forma invoice attached\r\nd...
5167    Subject: str _ rndlen ( 2 - 4 ) } { extra _ ti...
5168    Subject: check me out !\r\n61 bb\r\nhey derm\r...
5169    Subject: hot jobs\r\nglobal marketing specialt...
5170    Subject: save up to 89 % on ink + no shipping ...
Name: Text, Length: 5171, dtype: object

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=2529)

In [15]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3619,), (1552,), (3619,), (1552,))

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
tfidf=TfidfVectorizer(min_df=1,stop_words='english')

In [27]:
X_train_features = tfidf.fit_transform(X_train)

In [28]:
X_test_features=tfidf.transform(X_test)

In [29]:
X_train

869     Subject: re : lubrizol - bayport\r\ngerald lof...
3774    Subject: earn huge money quickly from home . ....
4834    Subject: the bull reccomends this stokkpic\r\n...
2348    Subject: copano p / l 01 / 00 - s 93481\r\ndar...
3314    Subject: tenaska iv agency fee\r\ncan you clar...
                              ...                        
4476    Subject: approval # 5146\r\nhello ,\r\nwe sent...
3656    Subject: cleburne issues\r\ndaren , with megan...
5039    Subject: look through the message - manager\r\...
4836    Subject: re [ 3 ] : talk with their meds\r\nth...
2876    Subject: please note my new email address\r\ne...
Name: Text, Length: 3619, dtype: object

In [30]:
X_train_features

<3619x40993 sparse matrix of type '<class 'numpy.float64'>'
	with 237389 stored elements in Compressed Sparse Row format>

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
rf= RandomForestClassifier(random_state=2529)

In [33]:
rf.fit(X_train_features,y_train)

RandomForestClassifier(random_state=2529)

In [34]:
y_pred=rf.predict(X_test_features)

In [35]:
y_pred.shape

(1552,)

In [36]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [37]:
rf.predict_proba(X_test_features)

array([[1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       ...,
       [0.98, 0.02],
       [1.  , 0.  ],
       [1.  , 0.  ]])

In [38]:
from sklearn.metrics import confusion_matrix,classification_report

In [39]:
print(confusion_matrix(y_test,y_pred))

[[1068   30]
 [   3  451]]


In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98      1098
           1       0.94      0.99      0.96       454

    accuracy                           0.98      1552
   macro avg       0.97      0.98      0.97      1552
weighted avg       0.98      0.98      0.98      1552

